src/frontend/routes/route_print.py
from pathlib import Path

import logging
from flask import render_template, Blueprint, abort
from src.functions import printout
from src.functions import settings

logger = logging.getLogger("print_logger")

setting = settings.Settings()

ROOT = Path(__file__).resolve().parent.parent.parent.parent
static = ROOT / "src" / "frontend" / "static" / "images"

print_bp = Blueprint("print_bp", __name__)

@print_bp.route("/printout", methods=["GET"])
def printing():
    """Print the created img."""
    setting.load_settings()
    save_path = static / "test_img_2.jpg"
    
    try:
        status_code = printout.print_image_cups(save_path, setting.get_setting("printer_name"))
        logger.info("LOG: print status code : %s", status_code)
        
        if status_code != 200:
            error_messages = {
                400: "Drucker nicht gefunden",
                500: "Unbekannter Fehler",
                501: "Papierstau",
                502: "Kein Papier",
                503: "Wenig Toner/Tinte",
                504: "Drucker-Neustart fehlgeschlagen",
                505: "Druckauftrag fehlgeschlagen"
            }
            error_message = error_messages.get(status_code, "Ein Fehler ist aufgetreten")
            return render_template("error_print.html", error_message=error_message), status_code
        
        return render_template("result.html", result_image_path=str(save_path))
    
    except Exception as e:
        return render_template("error_print.html", error_message=str(e)), 500


@print_bp.app_errorhandler(404)
def page_not_found(e):
    return render_template('error.html', error_message="Seite nicht gefunden"), 404

src/frontend/routes/route_qr_code.py
import os
from pathlib import Path
import datetime

from dotenv import load_dotenv

from flask import render_template, Blueprint
from src.functions.upload_image import upload_to_s3
from src.functions.make_qr_code import make_qr_code
from src.functions import settings

setting = settings.Settings()

ROOT = Path(__file__).resolve().parent.parent.parent.parent
static = ROOT / "src" / "frontend" / "static" / "images"


qr_code_bp = Blueprint("qr_code_bp", __name__)


@qr_code_bp.route("/qr_code", methods=["GET"])
def qr_code():
    """Show the QR Code to the users."""
    setting.load_settings()
    save_path = static / "test_img_2.jpg"
    dtobj = datetime.datetime.now()
    image_date = f"{dtobj.year}{dtobj.month}{dtobj.day}_{dtobj.hour}{dtobj.minute}{dtobj.second}"
    new_filename = image_date + "img.jpg"
    download_url = upload_to_s3(setting, save_path, new_filename)
    qr_img = make_qr_code(download_url)
    return render_template("qr_code.html", qr_code_data_uri=qr_img)

src/frontend/routes/route_setup_wifi.py
from pathlib import Path
import logging

from flask import Blueprint, request, jsonify, render_template
from src.frontend.routes import route_gst_pipes
from src.functions import settings, setup_wifi

setting = settings.Settings()

logger = logging.getLogger(__name__)

SUCCESS_REQUEST = 200

ROOT = Path(__file__).resolve().parent.parent.parent.parent
static = ROOT / "src" / "frontend" / "static" / "images"

wifi_bp = Blueprint("wifi_bp", __name__)

@wifi_bp.route('/barcode_scanner')
def barcode_scanner():

    _response, status_code = route_gst_pipes.start_pipeline()
    if status_code != SUCCESS_REQUEST:
        route_gst_pipes.stop_pipeline()
        route_gst_pipes.start_pipeline()
    return render_template('setup_wifi.html')

@wifi_bp.route("/setup-wifi", methods=["POST"])
def wifi():
    """Set the Wifi up."""
    barcode = request.json['barcode']
    print(barcode)
    setup_wifi.setup_wifi(barcode)
    return jsonify({'message': 'WLAN erfolgreich eingerichtet', "status": 200})

src/frontend/templates/config.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Config Page</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>
    <div class="content">
        <h1>File Upload and Display</h1><br>
        <p> Add Images for nice custom layouts or delete existing ones !</p>
        <p> Naming: with a number like 1, 2, 3 in the filenames they will be considered for the number of images selected by user <br>
            with "general" they will be considered for all as a backup</p>
        <div class="container">


            <a href="{{ url_for('wifi_bp.barcode_scanner') }}">
                <button>Setup the Wifi</button>
            <a href="{{ url_for('index') }}">
                <button>Back to Start</button>
            </a>
        </div>
    </div>
</body>
</html>

src/frontend/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error Page</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <script src="/static/autoRedirect.js"></script>
</head>
<body>
    <div class="container">
        <div class="left">
            <h1>Oh No something went Wrong!</h1>
            <p>just wait I will bring you back to safety</p>
        </div>
    </div>
</body>
</html>

src/frontend/templates/error_print.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error Page</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <style>
        button {
            margin-top: 10px;
            padding: 25px;
            border: none;
            cursor: pointer;
            font-size: 18px;
            border-radius: 8px;
            color: #fff;
            transition: background-color 0.3s ease, box-shadow 0.3s ease;
        }

        button.ok {
            background-color: #2ecc71;
        }

        button.ok:hover {
            background-color: #27ae60;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        .error-message {
            color: red;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="left">
            <h1>Oh No something went Wrong!</h1>
            <p>Just wait, I will bring you back to safety</p>
            {% if error_message %}
                <p class="error-message">Error: {{ error_message }}</p>
            {% endif %}
            <form action="/result/5" method="post">
                <button type="submit" class="ok" name="ok"
                        value="test_img_2.jpg">Ok habe ich geändert</button>
            </form>
        </div>
    </div>
</body>
</html>

src/frontend/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DaMu Photo App</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <style>
        .button {
            width: 150px; /* Adjust the width and height for the desired circle size */
            height: 150px;
            background-color: #ff4444;
            color: #fff;
            font-size: 16px;
            border: none;
            border-radius: 50%; /* Make the button a full circle */
            cursor: pointer;
            display: flex;
            align-items: center;
            justify-content: center;
            transition: background-color 0.3s ease, box-shadow 0.3s ease;
        }

        .button:hover {
            background-color: #e60000; /* Change color on hover */
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.3); /* Leichte Schattierung beim Hover */
        }

        /* Menu Icon Styling */
        .menu-icon {
            position: absolute;
            top: 10px;
            right: 10px;
            width: 30px;
            height: 30px;
            cursor: pointer;
            display: flex;
            flex-direction: column;
            justify-content: space-around;
            align-items: center;
        }

        .menu-icon div {
            width: 100%;
            height: 4px;
            background-color: black;
        }
    </style>
    <script>
        function openConfig() {
            window.location.href = "{{ url_for('config_bp.config') }}";
        }
    </script>
</head>
<body>
    <div class="menu-icon" onclick="openConfig()">
        <div></div>
        <div></div>
        <div></div>
    </div>
    <div class="container">
        <div class="left">
            <h1>{{ welcome_header }}</h1>
            <p> {{ welcome_text }}</p>
        </div>
        <div class="right">
            <button class="button" onclick="window.location.href='/select'">Buzzer drücken</button>
        </div>
    </div>
</body>
</html>

src/frontend/templates/preview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Image Preview</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
</head>
<body>
    <div class="container">
        <video id="video" width="640" height="480" autoplay></video>
        <div id="countdown">5</div>
    </div>
    <img id="capturedImage" style="display: none;">

    <script>
        var numInJavaScript = {{ num_images }};
        var originNum = {{ num_images }};
    </script>

    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
</body>
</html>

src/frontend/templates/qr_code.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Result</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <style>
        #container-local {
            display: flex;
            width: 80%;
            justify-content: space-between; /* Hinzugefügt, um den Raum zwischen den Containern zu maximieren */
            align-items: center; /* Vertikal zentrieren */
            background-color: #ffffff; /* Weiß für einen sauberen Look */
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        #image-container {
            max-width: 80%; /* Begrenzen Sie die Breite auf 80% des Bildschirms */
            margin-right: 20px; /* Abstand zwischen Bild und Buttons */
        }

        #buttons-container {
            display: flex;
            flex-direction: column;
            align-items: flex-end;
        }

        img {
            max-width: 80%;
        }

        button {
            margin-top: 10px;
            padding: 25px;
            border: none;
            cursor: pointer;
            font-size: 18px;
            border-radius: 8px; /* Runde Ecken für ein eleganteres Aussehen */
            color: #fff;
            transition: background-color 0.3s ease, box-shadow 0.3s ease;
        }

        button.cancel {
            background-color: #e74c3c; /* Dunkleres Rot für Abbrechen-Button */
        }

        button.print {
            background-color: #3498db; /* Farbe für Drucken-Button */
        }

        button.print:hover {
            background-color: #7f8c8d; /* Ändern Sie die Hintergrundfarbe beim Hover auf Grau */
                /* Andere Stile für den Hover-Effekt, falls gewünscht */
        }

        /* Hover-Effekte */
        button:hover {
            background-color: #34495e; /* Dunklere Hintergrundfarbe beim Hover */
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.3); /* Leichte Schattierung beim Hover */
        }
    </style>
    <script src="/static/autoRedirect.js"></script>
</head>
<body>
    <div id="container-local">
        <div id="image-container">
            <img id="qr_code_img" src="{{ qr_code_data_uri }}" alt="Result Image">
        </div>
        <div id="buttons-container">
            <form action="/result/5" method="post">
                <button type="submit" class="print" name="print"
                        value="test_img_2.jpg">Zurück</button>
            </form>
        </div>
    </div>
</body>
</html>

src/frontend/templates/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Result</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <style>
        #container-local {
            display: flex;
            width: 80%;
            justify-content: space-between; /* Hinzugefügt, um den Raum zwischen den Containern zu maximieren */
            align-items: center; /* Vertikal zentrieren */
            background-color: #ffffff; /* Weiß für einen sauberen Look */
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        #image-container {
            max-width: 80%; /* Begrenzen Sie die Breite auf 80% des Bildschirms */
            margin-right: 20px; /* Abstand zwischen Bild und Buttons */
        }

        #buttons-container {
            display: flex;
            flex-direction: column;
            align-items: flex-end;
        }

        img {
            max-width: 80%;
            max-height: 100vh;
            width: auto;
            height: auto;
            object-fit: contain;
        }

        button {
            margin-top: 10px;
            padding: 25px;
            border: none;
            cursor: pointer;
            font-size: 18px;
            border-radius: 8px; /* Runde Ecken für ein eleganteres Aussehen */
            color: #fff;
            transition: background-color 0.3s ease, box-shadow 0.3s ease;
        }

        button.cancel {
            background-color: #e74c3c; /* Dunkleres Rot für Abbrechen-Button */
        }

        button.upload-print {
            background-color: #2ecc71; /* Dunkleres Grün für Upload/Drucken-Button */
        }

        button.print {
            background-color: #3498db; /* Farbe für Drucken-Button */
        }

        button.print:hover {
            background-color: #7f8c8d; /* Ändern Sie die Hintergrundfarbe beim Hover auf Grau */
                /* Andere Stile für den Hover-Effekt, falls gewünscht */
        }

        /* Hover-Effekte */
        button:hover {
            background-color: #34495e; /* Dunklere Hintergrundfarbe beim Hover */
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.3); /* Leichte Schattierung beim Hover */
        }

        /* Menu Icon Styling */
        .menu-icon {
            position: absolute;
            top: 10px;
            right: 10px;
            width: 30px;
            height: 30px;
            cursor: pointer;
            display: flex;
            flex-direction: column;
            justify-content: space-around;
            align-items: center;
        }

        .menu-icon div {
            width: 100%;
            height: 4px;
            background-color: black;
        }
    </style>
    <script src="/static/autoRedirect.js"></script>
</head>
<body>
    <div id="container-local">
        <div id="image-container">
            <img src="{{ url_for('static', filename='images/test_img_2.jpg') }}" alt="Result Image">
        </div>
        <div id="buttons-container">
            <a href="{{ url_for('qr_code_bp.qr_code') }}">
                <button type="button" class="upload-print">Upload + QR Code</button>
            </a>
            <a href="{{ url_for('print_bp.printing') }}">
                <button type="button" class="print">Drucken</button>
            </a>
            <a href="{{ url_for('index') }}">
                <button type="button" class="cancel">Abbrechen</button>
            </a>
        </div>
    </div>
</body>
</html>

src/frontend/templates/select.html
<!-- templates/select.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DaMu Photobooth App</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <style>

        .container-local {
            text-align: center;
            width: 80%;
            background-color: #ffffff; /* Weiß für einen sauberen Look */
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            color: #333;
        }

        form {
            display: flex;
            flex-direction: row;
            justify-content: center;
            align-items: center;
            margin-top: 20px;
        }

        button {
            margin: 10px;
            padding: 20px;
            background-color: #5bc0de; /* Zartes Blau für den Button */
            border: 2px solid #31708f; /* Ein dunklerer Blauton für den Rand */
            border-radius: 10px;
            color: #fff; /* Weiße Schriftfarbe für Kontrast */
            font-size: 18px;
            cursor: pointer;
            transition: background-color 0.3s ease, transform 0.2s ease;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); /* Leichter Schatten für eine heitere Atmosphäre */
        }

        button:hover {
            background-color: #31708f; /* Dunkleres Blau auf Hover für Kontrast */
            transform: scale(1.05);
        }
    </style>
    <script src="/static/autoRedirect.js"></script>
</head>
<body>
    <div class="container-local">
        <h1>Bitte wähle die Anzahl an Bildern:</h1>
        <p></p>

        <form action="/select" method="post">
            <button type="submit" name="selected_option" value="1">1 Bild</button>
            <button type="submit" name="selected_option" value="2">2 Bilder</button>
            <button type="submit" name="selected_option" value="3">3 Bilder</button>
            <button type="submit" name="selected_option" value="4">4 Bilder</button>
        </form>
    </div>
</body>
</html>

src/frontend/templates/setup_wifi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Barcode Scanner</title>
    <style>
        #video {
            width: 100%;
            height: 100vh;
            object-fit: cover;
        }
        #cancel-button {
            position: absolute;
            top: 20px;
            left: 20px;
            padding: 10px 20px;
            font-size: 16px;
            background-color: #f44336;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <video id="video" autoplay></video>
    <button id="cancel-button" onclick="window.location.href='/config'">Abbrechen</button>
    <script type="module">
        import { BarcodeDetectorPolyfill } from 'https://cdn.jsdelivr.net/npm/@undecaf/barcode-detector-polyfill@0.9.21/dist/main.js';
        try {
            window['BarcodeDetector'].getSupportedFormats();
        } catch {
            window['BarcodeDetector'] = BarcodeDetectorPolyfill;
        }
    </script>
    <script>
        navigator.mediaDevices.getUserMedia({ video: true })
            .then(stream => {
                document.getElementById('video').srcObject = stream;
                const barcodeDetector = new BarcodeDetector();
                setInterval(() => {
                    barcodeDetector.detect(document.getElementById('video'))
                        .then(barcodes => {
                            if (barcodes.length > 0) {
                                const barcode = barcodes[0];
                                fetch('/setup-wifi', {
                                    method: 'POST',
                                    headers: {
                                        'Content-Type': 'application/json'
                                    },
                                    body: JSON.stringify({ barcode: barcode.rawValue })
                                })
                                .then(response => response.json())
                                .then(data => {
                                    console.log(data);
                                    // Umleitung zu config.html
                                    window.location.href = '/config';
                                })
                                .catch(error => console.error(error));
                            }
                        })
                        .catch(error => console.error(error));
                }, 1000);
            })
            .catch(error => console.error(error));
    </script>
</body>
</html>